import { Outfit } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Footer from "@/components/Footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "700"], // You can specify weights you need
});

export const metadata = {
  title: "Portrix - 3D Portfolio Builder",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <div className="overflow-hidden bg-background text-foreground no-scrollbar">
      <Header />
      <div className="mx-auto w-full px-3.5 overflow-auto h-screen">
        <div className=" my-container mx-auto">
        {children}
        </div>
      </div>

    </div>
  );
}
