import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/contexts/UserContext";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "700"], // You can specify weights you need
});

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${outfit.variable} antialiased`}>
        <UserProvider>
          <SidebarProvider defaultOpen={false}>
            <div className="w-full">

              <AppSidebar />

              {children}
              <Toaster
                duration={2000}
                toastOptions={{
                  classNames: {
                    success: '!bg-green-700 !text-white',
                    error: '!bg-red-700 !text-white',
                    info: '!bg-blue-500 !text-white',
                    warning: '!bg-yellow-500 !text-black',
                  },
                }}
              />
            </div>

          </SidebarProvider>

        </UserProvider>
      </body>
    </html >
  );
}
